### PR TITLE
Added docs describing how to run on a remote server

### PR DESCRIPTION
**Pull request by pkerpedjiev**
## Description

What was changed in this pull request?

- Added a short snippet about how to use when Juypter is running on a remote server

Why is it necessary?

Fixes #___

## Checklist

- [ ] Unit tests added or updated
- [x] Documentation added or updated
- [ ] Updated CHANGELOG.md
- [ ] Ran `black` on the root directory

### CODE REVIEW

**Review by gfudenberg — COMMENTED** [review]
looks good! I also had to put fuse=False

I wonder if it would also be useful to:
- add link to docs from higlass-python homepage (not just the icon, and maybe explaining that this takes you to the higlass-python section of the overall higlass docs)
- update the example.ipynb to link to this note in the `Local cooler files` section, b/c the `getting started` section on the higlass-python homepage links to this

**Comment by pkerpedjiev** [comment]
Thanks a ton for the suggestions!

I updated the Example.ipynb notebook and added a note about setting `fuse=False`. 

May I ask you to clarify what you mean be this?

> add link to docs from higlass-python homepage (not just the icon, and maybe explaining that this takes you to the higlass-python section of the overall higlass docs)

**Comment by gfudenberg** [comment]
I meant to add a section to the markdown after the getting started section, e.g. :
## Documentation

Take a look at the higlass-python section of the [higlass documentation](https://docs.higlass.io/jupyter.html)

**Comment by pkerpedjiev** [comment]
Ah, gotcha. Will do. Thank you!

**Pull request merged**
