### PR TITLE
support jupyterlab 3

### LINKED ISSUE #85: react version conflict
Config dir: /usr/local/etc/jupyter
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.2.2 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    voila.server_extension enabled
    - Validating voila.server_extension...
      voila.server_extension  OK

Config dir: /usr/local/etc/jupyter
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.2.2 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    voila.server_extension enabled
    - Validating voila.server_extension...
      voila.server_extension  OK

# /usr/local/bin/jupyter labextension install higlass-jupyter
An error occurred.
ValueError: The extension "higlass-jupyter" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLabExtension        Package
>=17.0.1 <18.0.0>=16.5.1 <17.0.0 react
>=17.0.1 <18.0.0>=16.5.1 <17.0.0 react-dom

### PR DESCRIPTION
**Pull request by alexlenail**
## Description

Support Jupyterlab 3

Why is it necessary?

Fixes #85

## Checklist

- [ ] Unit tests added or updated
- [ ] Update `examples.ipynb` notebook
- [ ] Documentation added or updated
- [ ] Updated CHANGELOG.md
- [ ] Ran `black` on the root directory

## Notes: 

https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-2-x-to-3-x

https://github.com/keplergl/kepler.gl/issues/1390#issuecomment-856176900

### CODE REVIEW

**Comment by alexlenail** [comment]
Huh, the numpy install is failing -- unlikely to have to do with this PR. Still worth fixing.

**Comment by nvictus** [comment]
Hmm... try unpinning [this](https://github.com/higlass/higlass-python/blob/master/requirements.txt#L2).
and [this](https://github.com/higlass/higlass-python/blob/master/requirements.txt#L7).

**Comment by nvictus** [comment]
Sorry, I just meant remove the strict version number requirements.

**Comment by alexlenail** [comment]
It seems like this is happening during a pandas install. It's trying to install pandas 1.0.4. That's a decently old version. 

```
Collecting pandas==1.0.4
  Downloading pandas-1.0.4.tar.gz (5.0 MB)
```

It's sort of unclear where this dependency is specified. Pandas is imported in the code a few times, but it doesn't show up in the requirements.txt. 

https://github.com/higlass/higlass-python/search?q=pandas

@nvictus

**Comment by nvictus** [comment]
Damnit, looks like [clodius](https://github.com/higlass/clodius/blob/develop/requirements.txt) is the culprit. @pkerpedjiev, are any of those `==` pinnings necessary? I'm sure the pandas one can be dropped.

**Comment by nvictus** [comment]
In any case, this PR is fine, so I'll merge.

**Pull request merged**
